# Generated by Django 5.2.7 on 2025-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo(s)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursos_atuacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso(s) de Atuação'),
        ),
    ]
