# Generated by Django 5.2.8 on 2025-11-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='remuneracao',
            field=models.CharField(default='Valor da remuneracao do processo seletivo', verbose_name='Valor da remuneracao do processo seletivo'),
            preserve_default=False,
        ),
    ]
