# Generated by Django 5.2.9 on 2025-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cursos_atuacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursos_atuacao',
            field=models.ManyToManyField(blank=True, related_name='professores_atuacao', to='contas.curso', verbose_name='Curso(s) de Atuação'),
        ),
    ]
