# Generated by Django 5.2.9 on 2025-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='periodo',
            field=models.CharField(choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período'), ('5', '5º Período'), ('6', '6º Período'), ('7', '7º Período'), ('8', '8º Período'), ('9', '9º Período'), ('10', '10º Período'), ('11', '11º Período'), ('12', '12º Período'), ('13', '13º Período'), ('14', '14º Período'), ('15', '15º Período'), ('16', '16º Período')], default='1', max_length=20, verbose_name='Período Atual'),
        ),
    ]
