# Generated by Django 5.2.7 on 2025-12-02 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('ENCERRADA', 'Encerrada')], default='APROVADA', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='contas.interesse'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='carga_horaria',
            field=models.CharField(max_length=50, verbose_name='Carga horária (Texto)'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='cursos_elegiveis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cursos elegíveis'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='horas_complementares',
            field=models.IntegerField(default=0, verbose_name='Horas Complementares (Total)'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='num_vagas',
            field=models.IntegerField(default=1, verbose_name='Número de vagas'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='processo_seletivo',
            field=models.TextField(blank=True, null=True, verbose_name='Processo seletivo'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='remuneracao',
            field=models.IntegerField(default=0, verbose_name='Remuneração (R$)'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='tipo',
            field=models.CharField(choices=[('MON', 'Monitoria Acadêmica'), ('IC', 'Iniciação Científica'), ('EST', 'Estágio'), ('LP', 'Laboratório de Pesquisa'), ('TMP', 'Trabalho Meio Período'), ('VOL', 'Voluntariado'), ('PAL', 'Palestra'), ('EQC', 'Equipe de Competição'), ('BOL', 'Bolsa'), ('OUT', 'Outro')], default='OUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedidooportunidade',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno PUC-Rio'), ('PROFESSOR', 'Professor/Gestor'), ('ALUNO_EXTERNO', 'Aluno de Fora')], default='ALUNO', max_length=20),
        ),
    ]
