# Generated by Django 5.2.7 on 2025-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_usuario_interesses_usuario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20),
        ),
    ]
