# Generated by Django 5.2.8 on 2025-11-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_oportunidade_remuneracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='horas_complementares',
            field=models.IntegerField(default=0, verbose_name='Número de horas complementares que a atividade oferece'),
            preserve_default=False,
        ),
    ]
