# Generated by Django 5.2.7 on 2025-12-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_oportunidade_criador_oportunidade_status_and_more'),
        ('contas', '0002_usuario_cargos_usuario_cursos_atuacao'),
    ]

    operations = [
    ]
