# Generated by Django 5.2.9 on 2025-12-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_usuario_cursos_atuacao_usuario_cursos_atuacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cursos_atuacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursos_atuacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso(s) de Atuação'),
        ),
    ]
