# Generated by Django 5.2.7 on 2025-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_merge_20251202_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='oportunidades/', verbose_name='Imagem de Capa'),
        ),
    ]
