# Generated by Django 5.2.7 on 2025-12-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_remove_usuario_cursos_atuacao_usuario_cursos_atuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='notificado_1_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='notificado_7_dias',
            field=models.BooleanField(default=False),
        ),
    ]
