# Generated by Django 5.2.7 on 2025-12-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_merge_20251202_1430'),
        ('contas', '0004_oportunidade_foto'),
    ]

    operations = [
    ]
