# Generated by Django 5.2.7 on 2025-11-26 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_remove_usuario_usuario_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidade',
            options={'verbose_name': 'Oportunidade', 'verbose_name_plural': 'Oportunidades'},
        ),
        migrations.RenameField(
            model_name='oportunidade',
            old_name='area',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='exigencias',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='horas_complementares',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='interessados',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='prazo_inscricao',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='status',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='local',
            field=models.TextField(default='Local não especificado (dados antigos)', help_text='Especifique a carga horária total e/ou semanal, bem como a quantidade de horas que podem ser aproveitadas como extensão', verbose_name='Local de realização da atividade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='tipo',
            field=models.CharField(choices=[('MON', 'Monitoria Acadêmica'), ('IC', 'Iniciação Científica'), ('EST', 'Estágio'), ('LP', 'Laboratório de Pesquisa'), ('OUT', 'Outro')], default='OUT', max_length=3),
        ),
    ]
