# Generated by Django 5.2.7 on 2025-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_oportunidade_notificado_1_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='notificado_1_dia',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='notificado_7_dias',
        ),
        migrations.AddField(
            model_name='favorito',
            name='notificado_1_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favorito',
            name='notificado_7_dias',
            field=models.BooleanField(default=False),
        ),
    ]
