# Generated by Django 5.2.7 on 2025-12-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_merge_0003_merge_20251202_1430_0004_oportunidade_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
