# Generated by Django 5.2.7 on 2025-11-26 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_oportunidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='carga_horaria',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Carga horária'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='cursos_elegiveis',
            field=models.CharField(default='Todos os cursos', max_length=255, verbose_name='Cursos elegíveis para participação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_encerramento',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Data de encerramento do processo seletivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='num_vagas',
            field=models.IntegerField(default=0, verbose_name='Número de vagas disponíveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='processo_seletivo',
            field=models.TextField(default='Processo seletivo não especificado para dados antigos', verbose_name='Processo seletivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='local',
            field=models.TextField(verbose_name='Local de realização da atividade'),
        ),
    ]
