# Generated by Django 5.2.8 on 2025-12-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_merge_0003_merge_20251202_1430_0004_oportunidade_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesse',
            options={'verbose_name': 'Interesse', 'verbose_name_plural': 'Interesses'},
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='related_interests',
            field=models.ManyToManyField(blank=True, related_name='oportunidades', to='contas.interesse'),
        ),
    ]
