# Generated by Django 5.2.7 on 2025-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_oportunidade_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='horas_complementares',
            field=models.IntegerField(default=0, verbose_name='Número de horas complementares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='remuneracao',
            field=models.IntegerField(default=0, verbose_name='Remuneracao'),
            preserve_default=False,
        ),
    ]
