# Generated by Django 5.2.8 on 2025-12-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_interesse_options_and_more'),
        ('contas', '0006_usuario_foto_perfil'),
    ]

    operations = [
    ]
